<?php

namespace TomGud\FoosLeader\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 *
	 */
	public function findByRole($role) {
	    $qb = $this->_em->createQueryBuilder();
	    $qb->select('u')
	            ->from($this->_entityName, 'u')
	            ->where('u.roles LIKE :roles')
	            ->setParameter('roles', '%"' . $role . '"%');
    return $qb->getQuery()->getResult();
	}
}
