<?php

namespace TomGud\FoosLeader\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 *
	 */
	public function findByRole($role) {
	    $qb = $this->_em->createQueryBuilder();
	    $qb->select('u')
	            ->from($this->_entityName, 'u')
	            ->where('u.roles LIKE :roles')
	            ->setParameter('roles', '%"' . $role . '"%');
        return $qb->getQuery()->getResult();
	}

    public function getActiveUsers() {
        $monthAgo = new \DateTime('now', new \DateTimeZone('utc'));
        $monthAgo->sub(\DateInterval::createFromDateString('1 month'));
        $qb = $this->createQueryBuilder('u');
        $qb
            ->innerJoin("TomGud\FoosLeader\CoreBundle\Entity\Result", "r", 'WITH',
                'u.id = r.player1 OR u.id = r.player2 OR u.id = r.player3 OR u.id = r.player4')
            ->where('r.submitted > :monthAgo')
            ->setParameter('monthAgo', $monthAgo);
        return $qb->getQuery()->getResult();
    }
}
