home:
    pattern:  /
    defaults: { _controller: FoosLeaderCoreBundle:Default:index }

new_result:
    pattern: /new_result
    defaults: { _controller: FoosLeaderCoreBundle:Result:new}
    methods: [GET]

create_result:
    pattern: /new_result
    defaults: { _controller: FoosLeaderCoreBundle:Result:create }
    methods: [POST]

detail_result:
    pattern: /result/{id}/
    defaults: { _controller: FoosLeaderCoreBundle:Result:detail }
    methods: [GET, POST]

confirm_result:
    pattern: /result/confirm/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:confirm }
    methods: [GET,POST]
    options:
        expose: true

invalidate_result:
    pattern: /result/invalidate/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:invalidateResult }
    methods: [GET,POST]
    options:
        expose: true

delete_result:
    pattern: /result/delete/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:delete }
    methods: [GET,POST]
    options:
        expose: true
