home:
    pattern:  /
    defaults: { _controller: FoosLeaderCoreBundle:Default:index }
    options:
        expose: true

new_result:
    pattern: /new_result
    defaults: { _controller: FoosLeaderCoreBundle:Result:new}
    methods: [GET]

create_result:
    pattern: /new_result
    defaults: { _controller: FoosLeaderCoreBundle:Result:create }
    methods: [POST]

detail_result:
    pattern: /result/{id}/
    defaults: { _controller: FoosLeaderCoreBundle:Result:detail }
    methods: [GET, POST]
    options:
          expose: true

confirm_result:
    pattern: /result/confirm/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:confirm }
    methods: [GET,POST]
    options:
        expose: true

invalidate_result:
    pattern: /result/invalidate/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:invalidateResult }
    methods: [GET,POST]
    options:
        expose: true

delete_result:
    pattern: /result/delete/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:delete }
    methods: [GET,POST]
    options:
        expose: true

claim_result_show:
    pattern: /result/claim/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:claimShow }
    methods: [GET]

claim_result_save:
    pattern: /result/claim/{id}
    defaults: { _controller: FoosLeaderCoreBundle:Result:claim }
    methods: [POST]

statistics_global:
    pattern: /stats
    defaults: { _controller: FoosLeaderCoreBundle:Statistics:global }
    methods: [GET]
    options:
            expose: true


api:
    resource: "@FoosLeaderCoreBundle/Resources/config/api/routing.yml"
    prefix: /api
